steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "app"
      - "deploy"
      - "app.yaml"
      - "cron.yaml"
      - "--quiet"
options:
  logging: CLOUD_LOGGING_ONLY
  serviceAccount: "projects/gcp-just-for/serviceAccounts/7080181112720-compute@developer.gserviceaccount.com"

timeout: "900s"
